config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  resources :addresses
  resources :uploads
  resources :translations
  resources :cards_logs
  resources :media
  resources :pages
  resources :sms_logs
  resources :notifications_settings
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :money_ops
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  get "operations_status" => "money_ops#operations_status" 
  get "wallets_status" => "user_wallets#wallets_status"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "/sitemap.xml" => "pages#sitemap", :format => "xml", :as => :sitemap
  get "facebook" => "media#facebook"
  post "facebook_post" => "media#facebook_post"
  get "change_locale" => "pages#change_locale"
  get "user_addresses" => "addresses#user_addresses"
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card"
      get "cards_status" => "cards#cards_status"
      resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :user_wallets
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      resources :notifications_settings
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :sms_logs
      resources :pages
      resources :cards_logs
      resources :addresses
      resources :uploads
      resources :translations
      get "user_addresses" => "addresses#user_addresses"
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      resources :notifications
      get "user_notifications" => "notifications#user_notifications"
    end
  end
end

app/models/translation.rb
class Translation < ApplicationRecord
    validates :controller, presence: true
    validates_uniqueness_of :text
end

app/controllers/api/v1/translations_controller.rb
module Api
  module V1
    class TranslationsController < ApplicationController
      before_action :set_translation, only: [:show, :edit, :update, :destroy]
      #respond_to :json
      # GET /translations
      # GET /translations.json
      def index

      # =begin
      # @api {get} /api/translations 1-Request translations List
      # @apiVersion 0.3.0
      # @apiName GetTranslation
      # @apiGroup Translations
      # @apiExample Example usage:
      # curl -i http://localhost:3000/api/translations
      # @apiSuccess {Number} id translation unique ID.
      # @apiSuccess {String} text original text.
      # @apiSuccess {String} arabic_translation arabic translation for text.
      # @apiSuccess {String} english_translation english translation for text.
      # @apiSuccess {Date} created_at  Date created.
      # @apiSuccess {Date} updated_at  Date Updated.
      # @apiSuccessExample Success-Response:
      # HTTP/1.1 200 OK
      # [
      #     {
      #         "id": 1,
      #         "text": "payers",
      #         "arabic_translation": "بايرز",
      #         "english_translation": "payers",
      #         "created_at": "2018-07-19T11:02:30.110Z",
      #         "updated_at": "2018-07-19T11:02:30.110Z",             
      #     },
      #     {
      #         "id": 2,
      #         "text": "welcome",
      #         "arabic_translation": "مرحبا",
      #         "english_translation": "welcome",
      #         "created_at": "2018-07-19T11:02:37.000Z",
      #         "updated_at": "2018-07-19T11:02:37.000Z",             
      #     }
      # ]
      # @apiError MissingToken invalid Token.
      # @apiErrorExample Error-Response:
      # HTTP/1.1 400 Bad Request
      #   {
      #     "error": "Missing token"
      #   }
      # =end

        @translations = Translation.all
        respond_to do |format|
          format.json { render json: @translations }
        end
      end

      # GET /translations/1
      # GET /translations/1.json
      def show
        # =begin
        # @api {get} /api/translations/{:id} 2-Request Specific translation
        # @apiVersion 0.3.0
        # @apiName GetSpecificTranslation
        # @apiGroup Translations
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/translations/5
        # @apiParam {Number} id translation ID.
        # @apiSuccess {String} text original text.
        # @apiSuccess {String} arabic_translation arabic translation for text.
        # @apiSuccess {String} english_translation english translation for text.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #     {
        #         "id": 5,
        #         "text": "test5",
        #         "arabic_translation": "اختبار",
        #         "english_translation": "test",
        #         "created_at": "2018-07-19T11:02:37.000Z",
        #         "updated_at": "2018-07-19T11:02:37.000Z",             
        #     }
        # @apiError TranslationNotFound The id of the Translation was not found. 
        # @apiErrorExample Error-Response:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "TranslationNotFound"
        #   }
        # @apiError MissingToken invalid token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        respond_to do |format|
          format.json { render json: Translation.find(params[:id]) }
        end

      end

      # GET /translations/new
      def new
        @translation = Translation.new
      end

      # GET /translations/1/edit
      def edit
      end

      # POST /translations
      # POST /translations.json
      def create
        # =begin
        # @api {post} /api/translations 3-Create a new translation
        # @apiVersion 0.3.0
        # @apiName PostTranslation
        # @apiGroup Translations
        # @apiParam {String} text original text.
        # @apiParam {String} arabic_translation arabic translation for text.
        # @apiParam {String} english_translation english translation for text.
        # @apiSuccess {Number} id new translation ID.
        # @apiSuccess {String} text original text.
        # @apiSuccess {String} arabic_translation arabic translation for text.
        # @apiSuccess {String} english_translation english translation for text.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #     {
        #         "id": 4,
        #         "text": "ahmad",
        #         "arabic_translation": "احمد حسن",
        #         "english_translation": "ahmad hassan",
        #         "created_at": "2018-07-19T15:09:07.000Z",
        #         "updated_at": "2018-07-19T15:09:07.000Z",             
        #     }
        # @apiError TranslationNotFound The id of the Translation was not found. 
        # @apiErrorExample Error-Response:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "TranslationNotFound"
        #   }
        # @apiError MissingToken invalid token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        # respond_to do |format|
        #   format.json { render json: Translation.create(translation_params) }
        # end

        respond_to do |format|
          @translation = Translation.new(translation_params)

            @text = params[:translation][:text].to_s
            @data_en = YAML.load_file "config/locales/en.yml"
            @data_ar = YAML.load_file "config/locales/ar.yml"
            @data_en["en"]["#{@text}"] = params[:translation][:english_translation].to_s
            @data_ar["ar"]["#{@text}"] = params[:translation][:arabic_translation].to_s
            File.open("config/locales/en.yml", 'w') { |f| YAML.dump(@data_en, f) }
            File.open("config/locales/ar.yml", 'w') { |f| YAML.dump(@data_ar, f) }

            format.json { render json: @translation }

        end
      end

      # PATCH/PUT /translations/1
      # PATCH/PUT /translations/1.json
      def update

        # =begin
        # @api {put} /api/translations/{:id} 4-Change an existing translation
        # @apiVersion 0.3.0
        # @apiName PutTranslation
        # @apiGroup Translations
        # @apiParam {Number} id translation ID.
        # @apiParam {String} arabic_translation arabic translation for text.
        # @apiParam {String} english_translation english translation for text.
        # @apiSuccess {String} text original text.
        # @apiSuccess {String} arabic_translation arabic translation for text.
        # @apiSuccess {String} english_translation english translation for text.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #     {
        #         "id": 4,
        #         "text": "ahmad",
        #         "arabic_translation": "احمد",
        #         "english_translation": "ahmad",
        #         "created_at": "2018-07-19T15:09:07.000Z",
        #         "updated_at": "2018-07-19T15:21:31.000Z",             
        #     }
        # @apiError MissingToken invalid token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        # respond_to do |format|
        #   format.json { render json: Translation.update(translation_params) }
        # end

        #respond_with Translation.update(translation_params)

        respond_to do |format|
          @translation.update(translation_params)

            @text = params[:translation][:text].to_s
            @data_en = YAML.load_file "config/locales/en.yml"
            @data_ar = YAML.load_file "config/locales/ar.yml"
            @data_en["en"]["#{@text}"] = params[:translation][:english_translation].to_s
            @data_ar["ar"]["#{@text}"] = params[:translation][:arabic_translation].to_s
            File.open("config/locales/en.yml", 'w') { |f| YAML.dump(@data_en, f) }
            File.open("config/locales/ar.yml", 'w') { |f| YAML.dump(@data_ar, f) }

            format.json { render json: Translation.update(translation_params) }

        end

      end

      # DELETE /translations/1
      # DELETE /translations/1.json
      def destroy
        
        # @translation.destroy
        # respond_to do |format|
        #   format.html { redirect_to translations_url, notice: 'Translation was successfully destroyed.' }
        #   format.json { head :no_content }
        # end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_translation
          @translation = Translation.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def translation_params
          params.require(:translation).permit(:text, :arabic_translation, :english_translation)
        end

    end

  end

end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  # GET /translations
  # GET /translations.json
  def index
    @translations = Translation.all
    respond_to do |format|
      format.html
      format.json { render json: @translations }
    end
  end

  # GET /translations/1
  # GET /translations/1.json
  def show
  end

  # GET /translations/new
  def new
    @translation = Translation.new
  end

  # GET /translations/1/edit
  def edit
  end

  # POST /translations
  # POST /translations.json
  def create
    @translation = Translation.new(translation_params)
    @text = params[:translation][:text].to_s
    @controller = params[:translation][:controller]
    @data_en = YAML.load_file "config/locales/en/#{@controller}.yml"
    @data_ar = YAML.load_file "config/locales/ar/#{@controller}.yml"
    @data_en["en"]["#{@controller}"]["#{@text}"] = params[:translation][:english_translation].to_s
    @data_ar["ar"]["#{@controller}"]["#{@text}"] = params[:translation][:arabic_translation].to_s
    File.open("config/locales/en/#{@controller}.yml", 'w') { |f| YAML.dump(@data_en, f) }
    File.open("config/locales/ar/#{@controller}.yml", 'w') { |f| YAML.dump(@data_ar, f) }

    respond_to do |format|
      if @translation.save
        format.html { redirect_to @translation, notice: 'Translation was successfully created.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translations/1
  # PATCH/PUT /translations/1.json
  def update
    respond_to do |format|
      if @translation.update(translation_params)

        @text = params[:translation][:text].to_s
        @controller = params[:translation][:controller]
        @data_en = YAML.load_file "config/locales/en/#{@controller}.yml"
        @data_ar = YAML.load_file "config/locales/ar/#{@controller}.yml"
        @data_en["en"]["#{@controller}"]["#{@text}"] = params[:translation][:english_translation].to_s
        @data_ar["ar"]["#{@controller}"]["#{@text}"] = params[:translation][:arabic_translation].to_s
        File.open("config/locales/en/#{@controller}.yml", 'w') { |f| YAML.dump(@data_en, f) }
        File.open("config/locales/ar/#{@controller}.yml", 'w') { |f| YAML.dump(@data_ar, f) }

        format.html { redirect_to @translation, notice: 'Translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translations/1
  # DELETE /translations/1.json
  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to translations_url, notice: 'Translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translation
      @translation = Translation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translation_params
      params.require(:translation).permit(:text, :arabic_translation, :english_translation , :controller)
    end
end

app/views/translations/_form.html.erb
<%= form_with(model: translation, local: true) do |form| %>
  <% if translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="field">
    <%= form.label :arabic_translation %>
    <%= form.text_field :arabic_translation %>
  </div>

  <div class="field">
    <%= form.label :english_translation %>
    <%= form.text_field :english_translation %>
  </div>

  <div class="field">
    <%= form.select :controller,options_for_select([['cards','cards'],['cards_logs','cards_logs'],['cards_categories','cards_categories'],
    ['user_wallets','user_wallets'],['wallets_transfer_ratios','wallets_transfer_ratios'],['money_ops','money_ops'],['media','media'],
    ['notifications_settings','notifications_settings'],['pages','pages'],['sms_logs','sms_logs'],['addresses','addresses']]),  {:include_blank => 'select controller'} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>
<%= form_with(model: @translation, local: true) do |form| %>
    <% if @translation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>
  
        <ul>
        <% @translation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :text %>
      <%= form.text_field :text , readonly: true %>
    </div>
  
    <div class="field">
      <%= form.label :arabic_translation %>
      <%= form.text_field :arabic_translation %>
    </div>
  
    <div class="field">
      <%= form.label :english_translation %>
      <%= form.text_field :english_translation %>
    </div>

    <div class="field">
    <%= form.label :controller %>
    <%= form.text_field :controller , readonly: true  %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<p id="notice"><%= notice %></p>

<h1 style= "padding-left: 15px;">Translations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Text</th>
      <th>Arabic translation</th>
      <th>English translation</th>
      <th>Controller</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= translation.text %></td>
        <td><%= translation.arabic_translation %></td>
        <td><%= translation.english_translation %></td>
        <td><%= translation.controller %></td>
        <td><%= link_to 'Show', translation %></td>
        <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
        <!-- <td><%# link_to 'Destroy', translation, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h5 style= "padding-left: 15px;"><%= link_to 'New Translation', new_translation_path %><h5>
<%= @ff%>
</body>

app/views/translations/new.html.erb
<h1>New Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @translation.text %>
</p>

<p>
  <strong>Arabic translation:</strong>
  <%= @translation.arabic_translation %>
</p>

<p>
  <strong>English translation:</strong>
  <%= @translation.english_translation %>
</p>

<p>
  <strong>Controller:</strong>
  <%= @translation.controller %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>