config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  resources :addresses
  resources :uploads
  resources :translations
  resources :cards_logs
  resources :media
  resources :pages
  resources :sms_logs
  resources :notifications_settings
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :money_ops
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  get "operations_status" => "money_ops#operations_status" 
  get "wallets_status" => "user_wallets#wallets_status"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "/sitemap.xml" => "pages#sitemap", :format => "xml", :as => :sitemap
  get "facebook" => "media#facebook"
  post "facebook_post" => "media#facebook_post"
  get "change_locale" => "pages#change_locale"
  get "user_addresses" => "addresses#user_addresses"
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card"
      get "cards_status" => "cards#cards_status"
      resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :user_wallets
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      resources :notifications_settings
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :sms_logs
      resources :pages
      resources :cards_logs
      resources :addresses
      resources :uploads
      resources :translations
      get "user_addresses" => "addresses#user_addresses"
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      resources :notifications
      get "user_notifications" => "notifications#user_notifications"
    end
  end
end

app/models/user_wallet.rb
class UserWallet < ApplicationRecord
    validates_uniqueness_of :uuid
    validates_uniqueness_of :user_id
    before_save :default_values

    # Add default values to currency and uuid before save
    def default_values
        self.currency ||= "USD"
        self.uuid ||= SecureRandom.hex(6)
    end

    # Check before confirming transfer balance between users
    # @param [Integer] userfrom The sender user ID.
    # @param [Integer] userto The receiver user ID.
    # @param [Float] transferamount The transferred amount between two users.
    # @return [message] error message if there is any error occurs while checking process.
    def self.checktransfer(user_from ,user_to ,transfer_amount)

        @user_from_exist = UserWallet.where(user_id: user_from.to_i).first
        @user_to_exist = UserWallet.where(user_id: user_to.to_i).first
        @max_transfer = WalletsTransferRatio.where(key: "max_transfer").pluck(:value).first
        @min_transfer = WalletsTransferRatio.where(key: "min_transfer").pluck(:value).first
        

        @message = ""

        if @user_from_exist != nil
            if @user_from_exist.amount.to_f < transfer_amount.to_f
                @message  = @message + "You don't have enough money for this operation"
            end

            if transfer_amount.to_f < @min_transfer.to_f
                @message  = @message + "Sorry, The transferd balance must be greater than #{@min_transfer} USD"
            end

            if transfer_amount.to_f > @max_transfer.to_f
                @message  = @message + "Sorry, The transferd balance must be less or equal than #{@max_transfer} USD"
            end

            if @user_from_exist.status == 0
                @message  = @message + "Sorry, Your Wallet was Disabled"
            end
        else
            @message  = @message + "The sender User Wasn't Stored in Our Database"
        end

        if @user_to_exist == nil
            @message  = @message + "The receiver User Wasn't Stored in Our Database"
        else
            if @user_to_exist.status == 0
                @message  = @message + "Sorry, The Receiver User Wallet was Disabled"
            end
        end      

        if user_from == user_to
            @message  = @message + "You can't transfer balance to yourself"
        end

        return   @message 
    end

end

app/controllers/api/v1/user_wallets_controller.rb
module Api
  module V1
    class UserWalletsController < ApplicationController
      before_action :set_user_wallet, only: [:show]
      skip_before_action :verify_authenticity_token

      # GET /user_wallets.json
      def index
        @user_wallets = UserWallet.all
        respond_to do |format|
          format.json { render json: @user_wallets }
        end

        # =begin
        # @api {get} /api/v1/user_wallets 1-Request Users Wallets List
        # @apiVersion 0.3.0
        # @apiName GetUserWallets
        # @apiGroup Users Wallets
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/user_wallets
        # @apiSuccess {Number} id User Wallet unique ID.
        # @apiSuccess {String} currency User Wallet Currency.
        # @apiSuccess {Float} amount User Wallet amount.
        # @apiSuccess {Number} user_id Wallet User ID.
        # @apiSuccess {Number} status User Wallet (0 for Disabled & 1 for Enabled).
        # @apiSuccess {String} uuid User Wallet Secure random number (Created automatically and must be 12 digits and letters).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # [
        #   {
        #       "id": 1,
        #       "currency": "USD",
        #       "amount": 1000,
        #       "user_id": 1,
        #       "status": 1,
        #       "uuid": "0fa993bcfa59",
        #       "created_at": "2018-08-02T11:03:14.634Z",
        #       "updated_at": "2018-08-02T13:51:18.183Z"
        #   },
        #   {
        #       "id": 2,
        #       "currency": "USD",
        #       "amount": 500,
        #       "user_id": 2,
        #       "status": 1,
        #       "uuid": "0b51db6a5988",
        #       "created_at": "2018-08-02T11:03:52.375Z",
        #       "updated_at": "2018-08-02T13:51:18.179Z"
        #   }
        # ]
        # @apiError MissingToken invalid Token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end
      end

      # GET /user_wallets/1
      def show
        # =begin
        # @api {get} /api/user_wallets/{:id} 2-Request Specific User Wallet
        # @apiVersion 0.3.0
        # @apiName GetSpecificUserWallet
        # @apiGroup Users Wallets
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/user_wallets/1
        # @apiParam {Number} id Card Operation ID.
        # @apiSuccess {Number} id User Wallet unique ID.
        # @apiSuccess {String} currency User Wallet Currency.
        # @apiSuccess {Float} amount User Wallet amount.
        # @apiSuccess {Number} user_id Wallet User ID.
        # @apiSuccess {Number} status User Wallet (0 for Disabled & 1 for Enabled).
        # @apiSuccess {String} uuid User Wallet Secure random number (Created automatically and must be 12 digits and letters).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #   {
        #       "id": 1,
        #       "currency": "USD",
        #       "amount": 1000,
        #       "user_id": 1,
        #       "status": 1,
        #       "uuid": "0fa993bcfa59",
        #       "created_at": "2018-08-02T11:03:14.634Z",
        #       "updated_at": "2018-08-02T13:51:18.183Z"
        #   }
        # @apiError WalletNotFound The id of this User Wallet was not found. 
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "Wallet Not Found"
        #   }
        # @apiError MissingToken invalid token.
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        flash[:error]= "User Wallet Not Found"
        respond_to do |format|
          if @user_wallet
            format.json { render json: @user_wallet }
          else
            format.json { render json: flash }
          end
        end

      end

      # GET /user_wallets/new
      def new
        @user_wallet = UserWallet.new
      end

      # POST /user_wallets.json
      def create

        # =begin
        # @api {post} /api/v1/user_wallets 3-Create a new User Wallet
        # @apiVersion 0.3.0
        # @apiName PostUserWallet
        # @apiGroup Users Wallets
        # @apiExample Example usage:
        # curl -X POST \
        # http://localhost:3000/api/v1/user_wallets \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        # "amount": "500",
        # "user_id": 3,
        # "status": 1
        # }'
        # @apiParam {Float} amount User Wallet amount.
        # @apiParam {Number} user_id Wallet User ID (unique).
        # @apiParam {Number} status User Wallet (0 for Disabled & 1 for Enabled).
        # @apiSuccess {Number} id User Wallet unique ID.
        # @apiSuccess {String} currency User Wallet Currency.
        # @apiSuccess {Float} amount User Wallet amount.
        # @apiSuccess {Number} user_id Wallet User ID.
        # @apiSuccess {Number} status User Wallet (0 for Disabled & 1 for Enabled).
        # @apiSuccess {String} uuid User Wallet Secure random number (Created automatically and must be 12 digits and letters).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #   {
        #       "id": 3,
        #       "currency": "USD",
        #       "amount": 500,
        #       "user_id": 3,
        #       "status": 1,
        #       "uuid": "0fa663bcsa47",
        #       "created_at": "2018-08-02T15:03:04.333Z",
        #       "updated_at": "2018-08-02T15:03:04.383Z"
        #   }
        # @apiError ExistingUserId User Id has already been taken.
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 Existing User Id
        #   {
        #     "error": "has already been taken"
        #   }
        # @apiError MissingToken invalid token .
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 422 Missing token
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        @user_wallet = UserWallet.new(user_wallet_params)

        respond_to do |format|
          if @user_wallet.save
            format.json { render json: @user_wallet, status: :created, location: @user_wallet }
          else
            format.json { render json: @user_wallet.errors, status: :unprocessable_entity }
          end
        end
      end

      def wallets_status

        # =begin
        # @api {get} /api/v1/wallets_status?id={:id} 4-Update a Specific User Wallet Status
        # @apiVersion 0.3.0
        # @apiName UpdateWalletsStatus
        # @apiGroup Users Wallets
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/wallets_status?id=2
        # @apiParam {Number} id User Wallet unique ID.
        # @apiParam {Number} status User Wallet (0 for Disabled & 1 for Enabled).
        # @apiSuccess {Number} status User Wallet (0 for Disabled & 1 for Enabled).
        # @apiSuccess {Number} id User Wallet unique ID.
        # @apiSuccess {String} currency User Wallet Currency.
        # @apiSuccess {Float} amount User Wallet amount.
        # @apiSuccess {Number} user_id Wallet User ID.
        # @apiSuccess {String} uuid User Wallet Secure random number (Created automatically and must be 12 digits and letters).
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #   {
        #       "id": 2,
        #       "currency": "USD",
        #       "amount": 500,
        #       "user_id": 2,
        #       "status": 0,
        #       "uuid": "0b51db6a5988",
        #       "created_at": "2018-08-02T11:03:52.375Z",
        #       "updated_at": "2018-08-02T13:51:18.179Z"
        #   }
        # @apiError WalletNotFound The id of this User Wallet was not found.  
        # @apiErrorExample Error-Response:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "User Wallet Not Found"
        #   }
        # =end

        @wallets_status = UserWallet.where(:id => params[:id].to_i).first
        flash[:error]= "User Wallet Not Found"

        respond_to do |format|
          if @wallets_status.status ==  0
            @wallets_status.update(:status => 1)
            format.json { render json: @wallets_status }
          elsif @wallets_status.status ==  1
            @wallets_status.update(:status => 0)
            format.json { render json: @wallets_status }
          else
            format.json { render json: flash }
          end
        end

      end

      def send_sms

        # =begin
        # @api {get} /api/v1/send_sms?tel={phone_number} 6-Send Verification SMS Code to Users
        # @apiVersion 0.3.0
        # @apiName SendSmsCode
        # @apiGroup Users Wallets
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/send_sms?tel=20106455****
        # @apiParam {Number} tel User phone number + country code.
        # @apiSuccess {Number} tel User phone number.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #   {
        #     "success": " Code was send successfully to number 201064****** "
        #   }
        # @apiError SendCodeFailed Something went wrong while sending SMS code.  
        # @apiErrorExample Error-Response:
        #   {
        #     "error": "Something wrong, Sending code was failed"
        #   }
        # =end

        @phone = params[:tel]
        respond_to do |format|

app/helpers/user_wallets_helper.rb
module UserWalletsHelper
end

app/views/user_wallets/_form.html.erb
<%= form_with(model: user_wallet, local: true) do |form| %>
  <% if user_wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_wallet.errors.count, "error") %> prohibited this user_wallet from being saved:</h2>

      <ul>
      <% user_wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :wallet_status %>
    <%= form.select :status,options_for_select([['Disabled',0],['Enabled',1]]),  {:include_blank => 'select status'} %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Wallets</h1>

<table>
  <thead>
    <tr>
      <th>Currency</th>
      <th>Amount</th>
      <th>User ID</th>
      <th>Status</th>
      <th>Uuid</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_wallets.each do |user_wallet| %>
      <tr>
        <td><%= user_wallet.currency %></td>
        <td><%= user_wallet.amount %></td>
        <td><%= user_wallet.user_id %></td>
        <% if user_wallet.status == 0 %>
        <td><%= "Disabled" %></td>
        <% elsif user_wallet.status == 1 %>
        <td><%= "Enabled" %></td>
        <% end %>
        <td><%= user_wallet.uuid %></td>
        <% if user_wallet.status == 0 %>
        <td><a href="/wallets_status?id=<%= user_wallet.id %>" class="btn btn-primary">Push To Enable This Wallet</a></td>
        <% else %>
        <td><a href="/wallets_status?id=<%= user_wallet.id %>" class="btn btn-primary">Push To Disable This Wallet</a></td>
        <% end %>
        <td><%= link_to 'Show', user_wallet %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Wallet', new_user_wallet_path %> |
<%= link_to 'Transfer Balance Between Users', transfer_balance_path %><br><br>
<%= link_to 'SMS Code Logs', sms_logs_path %>

app/views/user_wallets/new.html.erb
<h1>New User Wallet</h1>

<%= render 'form', user_wallet: @user_wallet %>

<%= link_to 'Back', user_wallets_path %>

app/views/user_wallets/send_sms.html.erb
<h1>Enable SMS Code</h1>

<%= form_tag  url_for(:controller => 'user_wallets', :action => 'send_sms_post'), :method => 'post' do %>

    <h4><%= t('Phone number preceded by country code') %></h4>
    <%= number_field_tag :tel %>


    <div style="margin-top:20px;">
        <button type="submit" ><%= t('Send Code') %> </button>
    </div>

  <% end %>

app/views/user_wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency:</strong>
  <%= @user_wallet.currency %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @user_wallet.amount %>
</p>

<p>
  <strong>User ID:</strong>
  <%= @user_wallet.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <% if @user_wallet.status == 0 %>
    <%= "Disabled" %>
  <% elsif @user_wallet.status == 1 %>
    <%= "Enabled" %>
  <% end %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @user_wallet.uuid %>
</p>

<%= link_to 'Back', user_wallets_path %>

app/views/user_wallets/transfer_balance.html.erb
<h1>User Wallets Transfer</h1>

<%= form_tag  url_for(:controller => 'user_wallets', :action => 'transfer_balancepost'), :method => 'post' do %>

    <h4><%= t('User From') %></h4>
    <%= number_field_tag :userfrom %>

    <h4><%= t('User To') %></h4>
    <%= number_field_tag :userto %>

    <h4><%= t('Amount') %></h4>
    <%= number_field_tag :transferamount %>

    <h4><%= t('User Phone') %></h4>
    <%= number_field_tag :tel %>

    <h4><%= t('User Email') %></h4>
    <%= email_field_tag :email %>

    <div style="margin-top:20px;">
        <button type="submit" ><%= t('Transfer Balance') %> </button>
    </div>

  <% end %>

app/views/user_wallets/transfer_balancepost.html.erb
<%# debug(@aa)%>

app/views/user_wallets/verifysms.html.erb
<h1>Verify SMS Code</h1>

<%= form_tag  url_for(:controller => 'user_wallets', :action => 'verifysms_post'), :method => 'post' do %>

    <h4><%= t('SMS Code') %></h4>
    <%= number_field_tag :code %>
  
  
    <div style="margin-top:20px;">
        <button type="submit" ><%= t('Verify Code') %> </button>
    </div>
  
  <% end %>

app/views/user_wallets/verifysms_post.html.erb
<%= debug(@aa)%>