config/routes.rb
Rails.application.routes.draw do

  resources :notifications
  resources :addresses
  resources :uploads
  resources :translations
  resources :cards_logs
  resources :media
  resources :pages
  resources :sms_logs
  resources :notifications_settings
  resources :wallets_transfer_ratios
  resources :user_wallets
  resources :money_ops
  resources :cards_categories
  resources :cards
  get "search" => "cards#search"
  post "search" => "cards#searchpost"
  get "buy_card" => "cards#buy_card" 
  get "cards_status" => "cards#cards_status"
  get "display_cards_categories" => "cards_categories#display_cards_categories"
  get "operations_status" => "money_ops#operations_status" 
  get "wallets_status" => "user_wallets#wallets_status"
  get "transfer_balance" => "user_wallets#transfer_balance"
  post "transfer_balance" => "user_wallets#transfer_balancepost"
  get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
  get "send_sms" => "user_wallets#send_sms"
  post "send_sms_post" => "user_wallets#send_sms_post"
  post "verifysms_post" => "user_wallets#verifysms_post"
  get "verifysms" => "user_wallets#verifysms"
  get "/sitemap.xml" => "pages#sitemap", :format => "xml", :as => :sitemap
  get "facebook" => "media#facebook"
  post "facebook_post" => "media#facebook_post"
  get "change_locale" => "pages#change_locale"
  get "user_addresses" => "addresses#user_addresses"
  get "search_address" => "addresses#search"
  post "search_address" => "addresses#searchpost"
  get "delete_user_addresses" => "addresses#delete_user_addresses"
  get "user_notifications" => "notifications#user_notifications"
  get "search_notifications" => "notifications#search"


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :cards
      get "search" => "cards#search"
      post "search" => "cards#searchpost"
      get "buy_card" => "cards#buy_card"
      get "cards_status" => "cards#cards_status"
      resources :cards_categories
      get "display_cards_categories" => "cards_categories#display_cards_categories"
      resources :money_ops
      get "operations_status" => "money_ops#operations_status"
      resources :user_wallets
      get "wallets_status" => "user_wallets#wallets_status"
      get "transfer_balance" => "user_wallets#transfer_balance"
      post "transfer_balance" => "user_wallets#transfer_balancepost"
      get "send_sms" => "user_wallets#send_sms"
      post "send_sms_post" => "user_wallets#send_sms_post"
      post "verifysms_post" => "user_wallets#verifysms_post"
      get "verifysms" => "user_wallets#verifysms"
      resources :notifications_settings
      get "add_defualt_notifications" => "notifications_settings#add_defualt_notifications"
      resources :sms_logs
      resources :pages
      resources :cards_logs
      resources :addresses
      resources :uploads
      resources :translations
      get "user_addresses" => "addresses#user_addresses"
      get "search_address" => "addresses#search"
      post "search_address" => "addresses#searchpost"
      get "delete_user_addresses" => "addresses#delete_user_addresses"
      resources :notifications
      get "user_notifications" => "notifications#user_notifications"
    end
  end
end

app/models/money_op.rb
class MoneyOp < ApplicationRecord
    validates_uniqueness_of :opid
    before_save :default_values

    # Add default value to opid before save
    def default_values
        self.opid ||= "PY"+[*('A'..'Z'),*('0'..'9')].to_a.shuffle[0,10].join
    end
end

app/controllers/api/v1/money_ops_controller.rb
module Api
  module V1
    class MoneyOpsController < ApplicationController
      before_action :set_money_op, only: [:show, :edit, :update, :destroy]
      skip_before_action :verify_authenticity_token

      # GET /money_ops.json
      def index
        
        @money_ops = MoneyOp.all
        respond_to do |format|
          format.json { render json: @money_ops }
        end

        # =begin
        # @api {get} /api/v1/money_ops 1-Request Money Operations List
        # @apiVersion 0.3.0
        # @apiName GetMoneyOperation
        # @apiGroup Money Operations
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/money_ops
        # @apiSuccess {Number} id Money Operation unique ID.
        # @apiSuccess {String} opid Operation unique number.
        # @apiSuccess {Number} optype Operation type (1 for Sent & 2 for Receive).
        # @apiSuccess {Number} amount Operation amount.
        # @apiSuccess {Number} payment_gateway  Operation payment gateway (paypal,bitcoin,...).
        # @apiSuccess {Number} status Operation status (0 for pending & 1 for compeleted).
        # @apiSuccess {Date} payment_date  Payment operation creation date.
        # @apiSuccess {Number} payment_id Payment ID for the operation itself.
        # @apiSuccess {Number} user_id Operation user.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # [
        #   {
        #       "id": 1,
        #       "opid": "PYZPRV18M7NT",
        #       "optype": 1,
        #       "amount": "150",
        #       "payment_gateway": 1,
        #       "status": 0,
        #       "payment_date": "2018-08-01T09:52:00.000Z",
        #       "payment_id": 3,
        #       "user_id": 1,
        #       "created_at": "2018-08-01T09:52:20.462Z",
        #       "updated_at": "2018-08-01T09:52:20.462Z"
        #   },
        #   {
        #       "id": 2,
        #       "opid": "PYTUGN80WB39",
        #       "optype": 1,
        #       "amount": "50",
        #       "payment_gateway": 1,
        #       "status": 0,
        #       "payment_date": "2018-08-01T09:52:00.000Z",
        #       "payment_id": 2,
        #       "user_id": 1,
        #       "created_at": "2018-08-01T09:52:56.776Z",
        #       "updated_at": "2018-08-01T09:52:56.776Z"
        #   }
        # ]
        # @apiError MissingToken invalid Token.
        # @apiErrorExample Error-Response:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end
      end

      # GET /money_ops/1.json
      def show
        # =begin
        # @api {get} /api/money_ops/{:id} 2-Request Specific Money Operation
        # @apiVersion 0.3.0
        # @apiName GetSpecificMoneyOperation
        # @apiGroup Money Operations
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/money_ops/2
        # @apiParam {Number} id Card Operation ID.
        # @apiSuccess {Number} id Money Operation unique ID.
        # @apiSuccess {String} opid Operation unique number.
        # @apiSuccess {Number} optype Operation type (1 for Sent & 2 for Receive).
        # @apiSuccess {Number} amount Operation amount.
        # @apiSuccess {Number} payment_gateway  Operation payment gateway (paypal,bitcoin,...).
        # @apiSuccess {Number} status Operation status (0 for pending & 1 for compeleted).
        # @apiSuccess {Date} payment_date  Payment operation creation date.
        # @apiSuccess {Number} payment_id Payment ID for the operation itself.
        # @apiSuccess {Number} user_id Operation user.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        #   {
        #       "id": 2,
        #       "opid": "PYTUGN80WB39",
        #       "optype": 1,
        #       "amount": "50",
        #       "payment_gateway": 1,
        #       "status": 0,
        #       "payment_date": "2018-08-01T09:52:00.000Z",
        #       "payment_id": 2,
        #       "user_id": 1,
        #       "created_at": "2018-08-01T09:52:56.776Z",
        #       "updated_at": "2018-08-01T09:52:56.776Z"
        #   }
        # @apiError CardNotFound The id of this Money Operation was not found. 
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "Card Not Found"
        #   }
        # @apiError MissingToken invalid token.
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 400 Bad Request
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        flash[:error]= "Money Operation Not Found"
        respond_to do |format|
          if @money_op
            format.json { render json: @money_op }
          else
            format.json { render json: flash }
          end
        end

      end

      # GET /money_ops/new
      def new
        @money_op = MoneyOp.new
      end


      # POST /money_ops.json
      def create

        # =begin
        # @api {post} /api/v1/money_ops 3-Create a new Money Operation
        # @apiVersion 0.3.0
        # @apiName PostMoneyOperation
        # @apiGroup Money Operations
        # @apiExample Example usage:
        # curl -X POST \
        # http://localhost:3000/api/v1/money_ops \
        # -H 'cache-control: no-cache' \
        # -H 'content-type: application/json' \
        # -d '{
        # "optype": 1,
        # "amount": "150",
        # "payment_gateway": 1,
        # "status": 0,
        # "payment_date": "2018-08-01T13:31:00.000Z",
        # "payment_id": 3,
        # "user_id": 1
        # }'
        # @apiSuccess {Number} id Money Operation unique ID.
        # @apiSuccess {String} opid Operation unique number (Created automatically and must be 12 digits and letters ).
        # @apiSuccess {Number} optype Operation type (1 for Sent & 2 for Receive).
        # @apiSuccess {Number} amount Operation amount.
        # @apiSuccess {Number} payment_gateway  Operation payment gateway (paypal,bitcoin,...).
        # @apiSuccess {Number} status Operation status (0 for pending & 1 for compeleted).
        # @apiSuccess {Date} payment_date  Payment operation creation date.
        # @apiSuccess {Number} payment_id Payment ID for the operation itself.
        # @apiSuccess {Number} user_id Operation user.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # {
        #   "id": 8,
        #   "opid": "PYL42W60CTGM",
        #   "optype": 1,
        #   "amount": "150",
        #   "payment_gateway": 1,
        #   "status": 0,
        #   "payment_date": "2018-08-01T13:31:00.000Z",
        #   "payment_id": 3,
        #   "user_id": 1,
        #   "created_at": "2018-08-01T11:33:49.055Z",
        #   "updated_at": "2018-08-01T11:33:49.055Z"
        # }
        # @apiError ExistingOperationId Operation Id has already been taken.
        # @apiErrorExample Error-Response1:
        # HTTP/1.1 Existing Operation Id
        #   {
        #     "error": "has already been taken"
        #   }
        # @apiError MissingToken invalid token .
        # @apiErrorExample Error-Response2:
        # HTTP/1.1 422 Missing token
        #   {
        #     "error": "Missing token"
        #   }
        # =end

        @money_op = MoneyOp.new(money_op_params)

        respond_to do |format|
          if @money_op.save
            format.json { render json: @money_op, status: :created, location: @money_op }
          else
            format.json { render json: @money_op.errors, status: :unprocessable_entity }
          end
        end

      end

      def operations_status

        # =begin
        # @api {get} /api/v1/operations_status?id={:id} 4-Update a Specific Operation Status
        # @apiVersion 0.3.0
        # @apiName UpdateOperationStatus
        # @apiGroup Money Operations
        # @apiExample Example usage:
        # curl -i http://localhost:3000/api/v1/operations_status?id=5
        # @apiSuccess {Number} id Money Operation unique ID.
        # @apiSuccess {String} opid Operation unique number.
        # @apiSuccess {Number} optype Operation type (1 for Sent & 2 for Receive).
        # @apiSuccess {Number} amount Operation amount.
        # @apiSuccess {Number} payment_gateway  Operation payment gateway (paypal,bitcoin,...).
        # @apiSuccess {Number} status Operation status (0 for pending & 1 for compeleted).
        # @apiSuccess {Date} payment_date  Payment operation creation date.
        # @apiSuccess {Number} payment_id Payment ID for the operation itself.
        # @apiSuccess {Number} user_id Operation user.
        # @apiSuccess {Date} created_at  Date created.
        # @apiSuccess {Date} updated_at  Date Updated.
        # @apiSuccessExample Success-Response:
        # HTTP/1.1 200 OK
        # {
        #   "status": 1,
        #   "id": 8,
        #   "opid": "PYL42W60CTGM",
        #   "optype": 1,
        #   "amount": "150",
        #   "payment_gateway": 1,
        #   "payment_date": "2018-08-01T13:31:00.000Z",
        #   "payment_id": 3,
        #   "user_id": 1,
        #   "created_at": "2018-08-01T11:33:49.055Z",
        #   "updated_at": "2018-08-01T15:45:10.000Z"
        # }
        # @apiError CardNotFound The ID of this Mony Operation was not found. 
        # @apiErrorExample Error-Response:
        # HTTP/1.1 404 Not Found
        #   {
        #     "error": "Card Not Found"
        #   }
        # =end

        @operations_status = MoneyOp.where(:id => params[:id].to_i).first
        flash[:error]= "Card Not Found"

        respond_to do |format|
            if @operations_status.status ==  0

app/helpers/money_ops_helper.rb
module MoneyOpsHelper
end

app/views/money_ops/_form.html.erb
<%= form_with(model: money_op, local: true) do |form| %>
  <% if money_op.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(money_op.errors.count, "error") %> prohibited this money_op from being saved:</h2>

      <ul>
      <% money_op.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :optype,options_for_select([['Sent',1],['Receive',2]]),  {:include_blank => 'select type'} %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :payment_gateway %>
    <%= form.number_field :payment_gateway %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status,options_for_select([['Pending',0],['Compeleted',1]]),  {:include_blank => 'select status'} %>
  </div>

  <div class="field">
    <%= form.label :payment_date %>
    <%= form.datetime_select :payment_date %>
  </div>

  <div class="field">
    <%= form.label :paymentid %>
    <%= form.number_field :payment_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/money_ops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Money Operartions</h1>

<table>
  <thead>
    <tr>
      <th>Operartion id</th>
      <th>Type</th>
      <th>Amount</th>
      <th>Payment gateway</th>
      <th>Status</th>
      <th>Payment date</th>
      <th>Payment id</th>
      <th>User id</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @money_ops.each do |money_op| %>
      <tr>
        <td><%= money_op.opid %></td>
        <% if money_op.optype == 1 %>
        <td><%= "Sent" %></td>
        <% elsif money_op.optype == 2 %>
        <td><%= "Receive" %></td>
        <% end %>
        <td><%= money_op.amount %></td>
        <td><%= money_op.payment_gateway %></td>
        <% if money_op.status == 0 %>
        <td><%= "Pending" %></td>
        <% elsif money_op.status == 1 %>
        <td><%= "Compeleted" %></td>
        <% end %>
        <td><%= money_op.payment_date %></td>
        <td><%= money_op.payment_id %></td>
        <td><%= money_op.user_id %></td>
        <% if money_op.status == 0 %>
        <td><a href="/operations_status?id=<%= money_op.id %>" class="btn btn-primary">Update status to Compeleted</a></td>
        <% else %>
        <td><a href="/operations_status?id=<%= money_op.id %>" class="btn btn-primary">Update status to Pending</a></td>
        <% end %>
        <td><%= link_to 'Show Details', money_op %></td>
        <!-- <td><%# link_to 'Update status', edit_money_op_path(money_op) %></td> -->
        <!-- <td><%# link_to 'Destroy', money_op, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Money Op', new_money_op_path %>

app/views/money_ops/new.html.erb
<h1>New Money Operation</h1>

<%= render 'form', money_op: @money_op %>

<%= link_to 'Back', money_ops_path %>

app/views/money_ops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operaion id:</strong>
  <%= @money_op.opid %>
</p>

<p>
  <strong>Type:</strong>
  <% if @money_op.optype == 1 %>
  <td><%= "Sent" %></td>
  <% elsif @money_op.optype == 2 %>
  <td><%= "Receive" %></td>
  <% end %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @money_op.amount %>
</p>

<p>
  <strong>Payment gateway:</strong>
  <%= @money_op.payment_gateway %>
</p>

<p>
  <strong>Status:</strong>
  <% if @money_op.status == 0 %>
  <td><%= "Pending" %></td>
  <% elsif @money_op.status == 1 %>
  <td><%= "Compeleted" %></td>
  <% end %>
</p>

<p>
  <strong>Payment date:</strong>
  <%= @money_op.payment_date %>
</p>

<p>
  <strong>Payment id:</strong>
  <%= @money_op.payment_id %>
</p>

<p>
  <strong>User id:</strong>
  <%= @money_op.user_id %>
</p>

<!-- <%# link_to 'Edit', edit_money_op_path(@money_op) %> -->
<%= link_to 'Back', money_ops_path %>